---
- name: Setup MPR Server
  hosts: vultr-mpr.makedeb.org
  remote_user: root
  roles:
    - {role: "setup_ssh", users: ["hwittenborn", "leo", "sshwifty"]}
    - setup_apt
    - setup_cloudflare
    - setup_scripts
    - setup_cron
    - mprweb
