---
- name: Setup Prebuilt-MPR CI Server
  hosts: vultr-prebuilt-mpr
  remote_user: root
  roles:
    - {role: "setup_ssh", users: ["hwittenborn", "sshwifty"]}
    - setup_apt
    - setup_scripts
    - setup_cron
    - prebuilt-mpr
